export const dummyTeams = [
  {
    teamName: '울산 현대 축구단',
    teamImg: 'public/assets/teams/울산현대.png',
    teamGrade: '1위',
    teamStadium: '울산 문수축구경기장',
    teamCardOwner: '999',
    totalMatching: '19392',
  },
  {
    teamName: '포항 스틸러스',
    teamImg: 'public/assets/teams/포항스틸러스.png',
    teamGrade: '2위',
    teamStadium: '포항스틸야드',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: 'FC 서울',
    teamImg: 'public/assets/teams/FC서울.png',
    teamGrade: '3위',
    teamStadium: '서울월드컵경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '제주 유나이티드 FC',
    teamImg: 'public/assets/teams/제주유나이티드.png',
    teamGrade: '4위',
    teamStadium: '제주월드컵경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '전북 현대 모터스',
    teamImg: 'public/assets/teams/전북현대모터스.png',
    teamGrade: '5위',
    teamStadium: '전주월드컵경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '대구 FC',
    teamImg: 'public/assets/teams/대구FC.png',
    teamGrade: '6위',
    teamStadium: 'DGB 대구은행파크',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '대전 하나 시티즌',
    teamImg: 'public/assets/teams/대전하나시티즌.png',
    teamGrade: '7위',
    teamStadium: '대전월드컵경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '광주 FC',
    teamImg: 'public/assets/teams/광주FC.png',
    teamGrade: '8위',
    teamStadium: '광주축구전용구장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '인천 유나이티드 FC',
    teamImg: 'public/assets/teams/인천유나이티드.png',
    teamGrade: '9위',
    teamStadium: '인천축구전용경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '수원 FC',
    teamImg: 'public/assets/teams/수원FC.png',
    teamGrade: '10위',
    teamStadium: '수원종합운동장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '강원 FC',
    teamImg: 'public/assets/teams/강원FC.png',
    teamGrade: '11위',
    teamStadium: '강릉종합운동장, 춘천 종합운동장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
  {
    teamName: '수원 삼성 블루윙즈',
    teamImg: 'public/assets/teams/수원삼성블루윙즈.png',
    teamGrade: '12위',
    teamStadium: '수원월드컵경기장',
    teamCardOwner: '1289',
    totalMatching: '19392',
  },
];
